// Comprehensive list of countries and their major cities
export const countriesData = [
  {
    name: "United States",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
    ],
  },
  {
    name: "United Kingdom",
    cities: [
      "London",
      "Birmingham",
      "Manchester",
      "Glasgow",
      "Liverpool",
      "Leeds",
      "Sheffield",
      "Edinburgh",
      "Bristol",
      "Cardiff",
    ],
  },
  {
    name: "Canada",
    cities: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
    ],
  },
  {
    name: "Australia",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Wollongong",
      "Hobart",
    ],
  },
  {
    name: "Germany",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
    ],
  },
  {
    name: "France",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],
  },
  {
    name: "Italy",
    cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
  },
  {
    name: "Spain",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Málaga",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Bilbao",
    ],
  },
  {
    name: "Netherlands",
    cities: [
      "Amsterdam",
      "Rotterdam",
      "The Hague",
      "Utrecht",
      "Eindhoven",
      "Tilburg",
      "Groningen",
      "Almere",
      "Breda",
      "Nijmegen",
    ],
  },
  {
    name: "Belgium",
    cities: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst"],
  },
  {
    name: "Switzerland",
    cities: ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"],
  },
  {
    name: "Sweden",
    cities: [
      "Stockholm",
      "Gothenburg",
      "Malmö",
      "Uppsala",
      "Västerås",
      "Örebro",
      "Linköping",
      "Helsingborg",
      "Jönköping",
      "Norrköping",
    ],
  },
  {
    name: "Norway",
    cities: [
      "Oslo",
      "Bergen",
      "Trondheim",
      "Stavanger",
      "Drammen",
      "Fredrikstad",
      "Kristiansand",
      "Sandnes",
      "Tromsø",
      "Sarpsborg",
    ],
  },
  {
    name: "Denmark",
    cities: [
      "Copenhagen",
      "Aarhus",
      "Odense",
      "Aalborg",
      "Esbjerg",
      "Randers",
      "Kolding",
      "Horsens",
      "Vejle",
      "Roskilde",
    ],
  },
  {
    name: "Finland",
    cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"],
  },
  {
    name: "Poland",
    cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"],
  },
  {
    name: "Czech Republic",
    cities: [
      "Prague",
      "Brno",
      "Ostrava",
      "Plzeň",
      "Liberec",
      "Olomouc",
      "České Budějovice",
      "Hradec Králové",
      "Ústí nad Labem",
      "Pardubice",
    ],
  },
  {
    name: "Austria",
    cities: [
      "Vienna",
      "Graz",
      "Linz",
      "Salzburg",
      "Innsbruck",
      "Klagenfurt",
      "Villach",
      "Wels",
      "Sankt Pölten",
      "Dornbirn",
    ],
  },
  {
    name: "Portugal",
    cities: [
      "Lisbon",
      "Porto",
      "Amadora",
      "Braga",
      "Setúbal",
      "Coimbra",
      "Queluz",
      "Funchal",
      "Cacém",
      "Vila Nova de Gaia",
    ],
  },
  {
    name: "Greece",
    cities: [
      "Athens",
      "Thessaloniki",
      "Patras",
      "Heraklion",
      "Larissa",
      "Volos",
      "Rhodes",
      "Ioannina",
      "Chania",
      "Chalcis",
    ],
  },
  {
    name: "Ireland",
    cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan"],
  },
  {
    name: "Japan",
    cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama"],
  },
  {
    name: "South Korea",
    cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"],
  },
  {
    name: "China",
    cities: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Chongqing",
      "Tianjin",
      "Wuhan",
      "Hangzhou",
      "Xi'an",
    ],
  },
  {
    name: "India",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat"],
  },
  {
    name: "Brazil",
    cities: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Porto Alegre",
    ],
  },
  {
    name: "Mexico",
    cities: [
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
      "León",
      "Juárez",
      "Zapopan",
      "Mérida",
      "San Luis Potosí",
    ],
  },
  {
    name: "Argentina",
    cities: [
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "La Plata",
      "San Miguel de Tucumán",
      "Mar del Plata",
      "Salta",
      "Santa Fe",
      "San Juan",
    ],
  },
  {
    name: "South Africa",
    cities: [
      "Johannesburg",
      "Cape Town",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
      "Bloemfontein",
      "East London",
      "Pietermaritzburg",
      "Benoni",
      "Vereeniging",
    ],
  },
  {
    name: "Nigeria",
    cities: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Zaria", "Aba"],
  },
  {
    name: "Egypt",
    cities: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Shubra El Kheima",
      "Port Said",
      "Suez",
      "Luxor",
      "Mansoura",
      "El-Mahalla El-Kubra",
      "Tanta",
    ],
  },
  {
    name: "Turkey",
    cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin"],
  },
  {
    name: "Russia",
    cities: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Kazan",
      "Nizhny Novgorod",
      "Chelyabinsk",
      "Samara",
      "Omsk",
      "Rostov-on-Don",
    ],
  },
  {
    name: "United Arab Emirates",
    cities: [
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Al Ain",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Umm Al Quwain",
      "Khor Fakkan",
      "Dibba Al-Fujairah",
    ],
  },
  {
    name: "Saudi Arabia",
    cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Buraidah", "Khamis Mushait", "Hofuf"],
  },
  {
    name: "Singapore",
    cities: ["Singapore"],
  },
  {
    name: "Malaysia",
    cities: [
      "Kuala Lumpur",
      "George Town",
      "Ipoh",
      "Shah Alam",
      "Petaling Jaya",
      "Johor Bahru",
      "Malacca City",
      "Kota Kinabalu",
      "Kuching",
      "Seremban",
    ],
  },
  {
    name: "Thailand",
    cities: [
      "Bangkok",
      "Chiang Mai",
      "Pattaya",
      "Phuket",
      "Hat Yai",
      "Nakhon Ratchasima",
      "Udon Thani",
      "Khon Kaen",
      "Nakhon Si Thammarat",
      "Chiang Rai",
    ],
  },
  {
    name: "Philippines",
    cities: [
      "Manila",
      "Quezon City",
      "Davao City",
      "Caloocan",
      "Cebu City",
      "Zamboanga City",
      "Taguig",
      "Antipolo",
      "Pasig",
      "Cagayan de Oro",
    ],
  },
  {
    name: "Indonesia",
    cities: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Bekasi",
      "Medan",
      "Tangerang",
      "Depok",
      "Semarang",
      "Palembang",
      "Makassar",
    ],
  },
  {
    name: "Vietnam",
    cities: [
      "Ho Chi Minh City",
      "Hanoi",
      "Da Nang",
      "Hai Phong",
      "Can Tho",
      "Bien Hoa",
      "Hue",
      "Nha Trang",
      "Buon Ma Thuot",
      "Vung Tau",
    ],
  },
  {
    name: "New Zealand",
    cities: [
      "Auckland",
      "Wellington",
      "Christchurch",
      "Hamilton",
      "Tauranga",
      "Napier-Hastings",
      "Dunedin",
      "Palmerston North",
      "Nelson",
      "Rotorua",
    ],
  },
]

export const getCountries = () => countriesData.map((c) => c.name).sort()

export const getCitiesByCountry = (country: string) => {
  const countryData = countriesData.find((c) => c.name === country)
  return countryData ? countryData.cities.sort() : []
}
