
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  maintenance_mode BOOLEAN DEFAULT FALSE,
  new_user_approval BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert a default settings row if it doesn't exist
INSERT INTO site_settings (id, maintenance_mode, new_user_approval)
SELECT 1, FALSE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM site_settings WHERE id = 1);

-- RLS Policies
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin full access" ON site_settings
  FOR ALL
  USING (is_admin(auth.uid()));
